version: '8.0.31'
services:
  db:
    image: mysql:8.0.31
    restart: always
    environment:
      MYSQL_DATABASE: 'DoorLocks'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'kleidaras'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'p0m0ll0$'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'p0m0ll0$'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      #- my-db:/var/lib/mysql
      - ./db_init:/docker-entrypoint-initdb.d
  broker:
    image: masstransit/rabbitmq:3.9.7
    ports:
        - 5672:5672
        - 15672:15672
    environment:
        - RABBITMQ_DEFAULT_USER=user
        - RABBITMQ_DEFAULT_PASS=password

